### ISSUE TITLE
Investigate HTTP500 when serving static JS files

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1058]
https://sentry.io/foodsaving-worldwide/karrot/issues/513031124/

```
Error: Request failed with status code 500
  at createError (./node_modules/axios/lib/core/createError.js:16:1)
  at settle (./node_modules/axios/lib/core/settle.js:18:1)
  at apply (./node_modules/axios/lib/adapters/xhr.js:77:1)
  at XMLHttpRequest.n (./node_modules/raven-js/src/raven.js:377:1)
```

**Comment by tiltec** [comment]
I probably was mistaken; this looks like the server returned 403 or 500 and the frontend isn't prepared for it. Could happen for a multitude of reasons, probably each of the events recorded by Sentry is caused by a different one (connections interrupted, server error, session timed out)
