### ISSUE TITLE
Exception: Nothing to use for text content, no text or html templates available.

### ISSUE THREAD

**Issue by lwm** [yunity/karrot-frontend#1265]
After raising https://github.com/yunity/karrot-docker/issues/4, I moved onto setup a local non-docker setup for the backend. I then ran into an issue related to missing tempaltes (although I can see them in the directory structure). I'm not sure where to go from here, so I am here for more help :) 

I see this when I run the tests on the backend.

So, here's the error:

```
Traceback (most recent call last):                                                                                                   
  File "manage.py", line 15, in <module>                                                                                             
    execute_from_command_line(sys.argv)                                                                                              
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()                                                                                                                        
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)                                                                          
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)                                                        
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)                                                                                             
  File "/home/decentral1se/yunity/karrot-backend/foodsaving/management/commands/create_sample_data.py", line 259, in handle            
    user = make_user()                                                                                  
  File "/home/decentral1se/yunity/karrot-backend/foodsaving/management/commands/create_sample_data.py", line 83, in make_user                                                 
    'mobile_number': faker.phone_number()                                                            
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/rest_framework/test.py", line 300, in post
    path, data=data, format=format, content_type=content_type, **extra)                         
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/rest_framework/test.py", line 213, in post
    return self.generic('POST', path, data, content_type, **extra)                                    
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/rest_framework/test.py", line 238, in generic
    method, path, data, content_type, secure, **extra)                                          
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/django/test/client.py", line 414, in generic
    return self.request(**r)                                                                                 
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/rest_framework/test.py", line 289, in request
    return super(APIClient, self).request(**kwargs)                                                           
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/rest_framework/test.py", line 241, in request
    request = super(APIRequestFactory, self).request(**kwargs)                                              
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/django/test/client.py", line 495, in request
    raise exc_value                                                                                                  
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)                                                        
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view                                               
    return view_func(*args, **kwargs)                                                                                                                                                                              
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/decentral1se/yunity/karrot-backend/foodsaving/userauth/api.py", line 55, in post
    serializer.save()
  File "/home/decentral1se/.pyenv/versions/karrot-backend/lib/python3.7/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/home/decentral1se/yunity/karrot-backend/foodsaving/userauth/serializers.py", line 86, in create
    user = self.Meta.model.objects.create_user(**validated_data)
  File "/home/decentral1se/yunity/karrot-backend/foodsaving/users/models.py", line 57, in create_user
    return self._create_user(email, password, display_name, **extra_fields)
  File "/home/decentral1se/.pyenv/versions/3.7.1/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/decentral1se/yunity/karrot-backend/foodsaving/users/models.py", line 48, in _create_user
    user.send_welcome_email()
  File "/home/decentral1se/.pyenv/versions/3.7.1/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/decentral1se/yunity/karrot-backend/foodsaving/users/models.py", line 152, in send_welcome_email
    prepare_signup_email(user=self, verification_code=verification_code).send()
  File "/home/decentral1se/yunity/karrot-backend/foodsaving/users/emails.py", line 65, in prepare_signup_email
    transactional=True,
  File "/home/decentral1se/yunity/karrot-backend/foodsaving/utils/email_utils.py", line 99, in prepare_email
    subject, text_content, html_content = prepare_email_content(template, context, language)
  File "/home/decentral1se/yunity/karrot-backend/foodsaving/utils/email_utils.py", line 158, in prepare_email_content
    raise Exception('Nothing to use for text content, no text or html templates available.')
Exception: Nothing to use for text content, no text or html templates available.
```

And my `config/local_settings.py` is:

```
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'karrot-backend',
        'USER': 'karrot-backend',
        'PASSWORD': 'passw0rd',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

SECRET_KEY = 'c*#4=n$s4!*gdgq3nora#a$*xznctg-6=4_edeg9^dsxk&=p=$'
DEBUG = True

# needed for deployment
STATIC_ROOT = './static/'
ALLOWED_HOSTS = ['*']

# Uploaded files location, e.g. user photos
MEDIA_ROOT = './uploads/'
MEDIA_URL = '/media/'

######
# Mail configuration
# Uses the console backend for local development
# Set the sparkpost key on deploy
######

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


ANYMAIL = {
    # Should be a subaccount to receive webhooks scoped to this account
    # https://app.sparkpost.com/account/subaccounts
    # Transmissions: Read/Write
    # Event Webhooks: Read/Write
    "SPARKPOST_API_KEY": "your subaccount key"
}
# to set up a relay webhook for incoming emails
# https://developers.sparkpost.com/api/relay-webhooks.html
SPARKPOST_ACCOUNT_KEY = 'your account key'
SPARKPOST_RELAY_DOMAIN = 'replies.your-karrot-deployment'

# shared secrets, will be used by setup_sparkpost management command
SPARKPOST_RELAY_SECRET = 'generate a random string'
SPARKPOST_WEBHOOK_SECRET = 'generate another random string'

DEFAULT_FROM_EMAIL = "admin@foobar.com"  # can be anything if using the console backend
HOSTNAME = 'https://localhost:8000'  # for constructing the frontend URL
SITE_NAME = 'karrot.world' # used as human readable site name, for example in e-mail templates


######
# InfluxDB config for statistics reporting
# Disabled by default
######

INFLUXDB_DISABLED = True
INFLUXDB_HOST = '127.0.0.1'
INFLUXDB_PORT = '8086'
INFLUXDB_USER = ''
INFLUXDB_PASSWORD = ''
INFLUXDB_DATABASE = 'fstool'
INFLUXDB_TAGS_HOST = 'yuca'
INFLUXDB_TIMEOUT = 2
INFLUXDB_USE_CELERY = False
INFLUXDB_USE_THREADING = True

######
# Firebase Cloud Messaging config
# For sending push messages
# Get one from https://console.firebase.google.com
######

FCM_SERVER_KEY = 'your server key'

#######
# Sentry.io config for error reporting
# Only needs to be enabled on deploy
########

# import os
# import raven

# RAVEN_CONFIG = {
#    'dsn': 'https://f4b3de91ad384e4ca0d371c591cf3904:60760787f4464c5293afa6fe877d3d9d@sentry.io/147126',
#    # If you are using git, you can also automatically configure the
#    # release based on the git info.
#    'release': raven.fetch_git_sha(os.path.dirname(os.pardir)),
#}

######
# Logger configuration proposal:
# Disables most console logging as well as django admin email logging
# and sends all errors to sentry.
######

#LOGGING = {
#    'version': 1,
#    'disable_existing_loggers': False,
#    'formatters': {
#        'verbose': {
#            'format': '%(levelname)s %(asctime)s %(module)s '
#                      '%(process)d %(thread)d %(message)s'
#        },
#    },
#    'handlers': {
#        'sentry': {
#            'level': 'WARNING',
#            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler',
#        },
#        'console': {
#            'level': 'WARNING',
#            'class': 'logging.StreamHandler',
#            'formatter': 'verbose'
#        }
#
#    },
#    'loggers': {
#        'raven': {
#            'level': 'WARNING',
#            'handlers': ['console'],
#            'propagate': False,
#        },
#        'sentry.errors': {
#            'level': 'WARNING',
#            'handlers': ['console'],
#            'propagate': False,
#        },
#        'django': { # Disable django admin email logging by overriding
#            'level': 'ERROR',
#            'handlers': ['sentry'],
#        }
#    },
#    'root': {
#        'level': 'ERROR',
#        'handlers': ['sentry'],
#     },
#}

#HUEY = {
#    'always_eager': False,
#    'connection': {
#        'host': REDIS_HOST,
#    },
#    'consumer': {
#        'workers': 8,
#        'worker_type' : 'greenlet',
#    },
#}
```

**Comment by lwm** [comment]
PS. I'll update https://github.com/yunity/karrot-backend/blob/master/SETUP.md once I get setup too.

**Comment by nicksellen** [comment]
Ah, you need to convert the templates from mjml format into nice jinja2 ones that can be used by the backend, `cd mjml && yarn && ./convert` should do the trick.

There is a little bit about this in the context of the email template viewer https://github.com/yunity/karrot-backend#email-template-viewer.

Perhaps we should add the mjml step into the `sync.py` script... what do you think @tiltec?

(in the docker-compose setup it's handled in a seperate container, and runs in the watch mode)

**Comment by tiltec** [comment]
> Perhaps we should add the mjml step into the sync.py script... what do you think @tiltec?

Sounds good! Could even clear out old html files, that caused me some test failures once when switching between branches

**Comment by nicksellen** [comment]
> Sounds good! Could even clear out old html files, that caused me some test failures once when switching between branches

That's added and merged now.

**Comment by lwm** [comment]
Did the trick! Thanks to you both :rocket: :rocket: :rocket:
