### ISSUE TITLE
TypeError: Cannot read property 'removeEventListener' of undefined

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#651]
Looks like it's http://forum.quasar-framework.org/topic/382/popover-removeeventlistener-error-in-beforedestroy although that said it was already fixed in quasar. So might not be exactly that, but related.

https://sentry.io/foodsaving-worldwide/karrot/issues/394088575/

```
TypeError: Cannot read property 'removeEventListener' of undefined
  at a.beforeDestroy (/js/vendor.87d0c5a8937f81917d63.js:11:131808)
  at Pt (/js/vendor.87d0c5a8937f81917d63.js:6:12003)
  at a.t.$destroy (/js/vendor.87d0c5a8937f81917d63.js:6:44487)
  at destroy (/js/vendor.87d0c5a8937f81917d63.js:6:42266)
  at y (/js/vendor.87d0c5a8937f81917d63.js:6:52655)
...
(33 additional frame(s) were not displayed)
```

**Comment by tiltec** [comment]
Is fixed upstream, will get released with quasar 0.14.7
https://github.com/quasarframework/quasar/pull/1043
