### ISSUE TITLE
end2end tests interfere with vuelidate

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#737]
Hammerhead.js is the test proxy of testcafe, it seems to cause problems with vuelidate (and I think also some other vuejs parts)

https://sentry.io/foodsaving-worldwide/karrot/issues/403444035/

```
Error: Cannot read property '__isVuelidateAsyncVm' of undefined
  at Function.t._error (/hammerhead.js:2:2619)
  at value (/hammerhead.js:2:16693)
  at a.proxy (/ByDNSWUJM!s!utf-8/http://localhost:8080/js/0.b10023889641ee4a6df6.js:14:145145)
  at xr.get (/ByDNSWUJM!s!utf-8/http://localhost:8080/js/vendor.6d5a0794315c455965d9.js:7:44784)
  at xr.evaluate (/ByDNSWUJM!s!utf-8/http://localhost:8080/js/vendor.6d5a0794315c455965d9.js:7:45849)
...
(45 additional frame(s) were not displayed)
```

**Comment by tiltec** [comment]
Might be solved by fixing the `inList` validator, will close for now.
