### ISSUE TITLE
Investigate quasar problem when selecting language in settings (mobile Safari)

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#745]
https://sentry.io/foodsaving-worldwide/karrot/issues/403820471/

```
TypeError: null is not an object (evaluating 'e.length')
  at apply (./node_modules/quasar-framework/dist/quasar.esm.js:2778:1)
  at wrapped (./node_modules/raven-js/src/raven.js:347:1)
```

**Comment by tiltec** [comment]
Closing because the language chooser was removed from settings and this error didn't occur again.
