### ISSUE TITLE
Investigate failing invitation send on mobile safari

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#785]
https://sentry.io/foodsaving-worldwide/karrot/issues/408314440/

```
NotFoundError: The object can not be found here.
  at removeChild ([native code])
  at close (./node_modules/quasar-framework/dist/quasar.esm.js:7036:1)
  at call (./node_modules/quasar-framework/dist/quasar.esm.js:7106:1)
  at callHook (./node_modules/vue/dist/vue.runtime.esm.js:2864:1)
  at $destroy (./node_modules/vue/dist/vue.runtime.esm.js:2649:1)
...
(15 additional frame(s) were not displayed)
```

**Comment by tiltec** [comment]
(This is on Safari 11, so it's unrelated to #786 )

**Comment by tiltec** [comment]
Can't see the sentry error anymore...
