### ISSUE TITLE
Result of emptySlots calculation in PickupUsers can throw "invalid array length" error

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#787]
See sentry below

https://sentry.io/foodsaving-worldwide/karrot/issues/406704685/

```
RangeError: invalid array length
  at renderList (./node_modules/vue/dist/vue.runtime.esm.js:3633:1)
  at render (./src/components/Pickups/PickupUsers.vue?77f2:1:1005)
  at vm (./node_modules/vue/dist/vue.runtime.esm.js:4407:1)
  at this (./node_modules/vue/dist/vue.runtime.esm.js:2697:1)
  at this (./node_modules/vue/dist/vue.runtime.esm.js:3040:1)
...
(45 additional frame(s) were not displayed)
```

**Comment by tiltec** [comment]
Should be fixed with #814
