### ISSUE TITLE
[CI build-docs] Cannot find module 'asciidoctor.js'

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#816]
The `build-docs` job is a bit flakey in CircleCI, it sometimes throws errors like these:

https://circleci.com/gh/yunity/karrot-frontend/5956

```
Error loading version latest: Error: Cannot find module 'asciidoctor.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/circleci/.gitbook/versions/3.2.3/node_modules/gitbook-asciidoc/lib/toHTML.js:1:81)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

TypeError: Cannot read property 'commands' of null
error Command failed with exit code 1.
```

I suppose something with gitbooks own npm install does not work correctly, maybe caching of node_modules interferes with it?

**Comment by tiltec** [comment]
Didn't happen again.
