### ISSUE TITLE
yarn command throws error

### ISSUE THREAD

**Issue by MuskanSapolia** [yunity/karrot-frontend#942]
When installing dependencies with `yarn` ,it throws following error:
```
Arguments: -c node-gyp rebuild
Directory: /home/muskan/Desktop/karrot-frontend/node_modules/canvas
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | linux | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp http GET https://nodejs.org/dist/v8.9.4/node-v8.9.4-headers.tar.gz
gyp http 200 https://nodejs.org/dist/v8.9.4/node-v8.9.4-headers.tar.gz
gyp http GET https://nodejs.org/dist/v8.9.4/SHASUMS256.txt
gyp http 200 https://nodejs.org/dist/v8.9.4/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/muskan/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/muskan/Desktop/karrot-frontend/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/muskan/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/muskan/.node-gyp/8.9.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/muskan/.node-gyp/8.9.4',
gyp info spawn args   '-Dnode_gyp_dir=/home/muskan/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/muskan/.node-gyp/8.9.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/muskan/Desktop/karrot-frontend/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/muskan/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command \"/home/muskan/.nvm/versions/node/v8.9.4/bin/node\" \"/home/muskan/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /home/muskan/Desktop/karrot-frontend/node_modules/canvas
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok".
```

**Comment by tiltec** [comment]
That's a known requirement of `canvas` to have `libcairo` installed: https://stackoverflow.com/questions/22100213/package-cairo-was-not-found-in-the-pkg-config-search-path-node-j-s-install-canv

Find instructions how to do so here: https://github.com/Automattic/node-canvas#installation

Alternatively, you can use our docker-compose installation that has everything ready for you (including the backend). Might be a bit overkill if you only want to do frontend development: https://github.com/yunity/karrot-docker

**Comment by MuskanSapolia** [comment]
It is resolved. Thankyou :)
